export const DEFAULT_LANGUAGES_CODE = {
  VN: 'vi',
  EN: 'en',
  KR: 'ko',
};

export const LANGUAGE_CODES_MAP = {
  af: 'ZA',
  sq: 'AL',
  am: 'ET',
  ar: 'AE',
  bn: 'BD',
  bg: 'BG',
  'zh-CN': 'CN',
  'zh-TW': 'CN',
  da: 'DK',
  nl: 'NL',
  en: 'UK',
  et: 'EE',
  fil: 'PH',
  fi: 'FI',
  fr: 'FR',
  de: 'DE',
  el: 'GR',
  he: 'IL',
  hi: 'IN',
  hu: 'HU',
  is: 'IS',
  id: 'ID',
  ga: 'IE',
  it: 'IT',
  ja: 'JP',
  ko: 'KR',
  lo: 'LA',
  lv: 'LV',
  lt: 'LT',
  mg: 'MG',
  ms: 'MY',
  mt: 'MT',
  mi: 'NZ',
  mn: 'MN',
  ne: 'NP',
  no: 'NO',
  ps: 'AF',
  fa: 'AF',
  pl: 'PL',
  pt: 'PT',
  ro: 'RO',
  ru: 'RU',
  sr: 'RS',
  sk: 'SK',
  es: 'ES',
  sw: 'KE',
  sv: 'SE',
  tl: 'PH',
  tg: 'TJ',
  ta: 'LK',
  th: 'TH',
  tr: 'TR',
  uk: 'UA',
  ur: 'PK',
  vi: 'VN',
  cy: 'GB-WLS',
};

export const SUPPORTED_LANGUAGES = [
  { code: 'af', name: 'Afrikaans' },
  { code: 'sq', name: 'Albanian' },
  { code: 'am', name: 'Amharic' },
  { code: 'ar', name: 'Arabic' },
  { code: 'bn', name: 'Bengali' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'zh-CN', name: 'Chinese (Simplified)' },
  { code: 'zh-TW', name: 'Chinese (Traditional)' },
  { code: 'da', name: 'Danish' },
  { code: 'nl', name: 'Dutch' },
  { code: 'en', name: 'English' },
  { code: 'et', name: 'Estonian' },
  { code: 'fil', name: 'Filipino' },
  { code: 'fi', name: 'Finnish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'el', name: 'Greek' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hi', name: 'Hindi' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'is', name: 'Icelandic' },
  { code: 'id', name: 'Indonesian' },
  { code: 'ga', name: 'Irish Gaelic' },
  { code: 'it', name: 'Italian' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'lo', name: 'Lao' },
  { code: 'lv', name: 'Latvian' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'ms', name: 'Malay' },
  { code: 'mt', name: 'Maltese' },
  { code: 'mi', name: 'Maori' },
  { code: 'mn', name: 'Mongolian' },
  { code: 'ne', name: 'Nepali' },
  { code: 'no', name: 'Norwegian' },
  { code: 'ps', name: 'Pashto' },
  { code: 'fa', name: 'Persian' },
  { code: 'pl', name: 'Polish' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ro', name: 'Romanian' },
  { code: 'ru', name: 'Russian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'sk', name: 'Slovak' },
  { code: 'es', name: 'Spanish' },
  { code: 'sw', name: 'Swahili' },
  { code: 'sv', name: 'Swedish' },
  { code: 'tl', name: 'Filipino' },
  { code: 'tg', name: 'Tajik' },
  { code: 'ta', name: 'Tamil' },
  { code: 'th', name: 'Thai' },
  { code: 'tr', name: 'Turkish' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'ur', name: 'Urdu' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'cy', name: 'Welsh' },
];

export const SUPPORTED_VOICE_MAP = {
  af: 'af',
  sq: 'sq-AL',
  am: 'am-ET',
  ar: 'ar-EG',
  bn: 'bn-BD',
  bg: 'bg',
  'zh-CN': 'zh-CN',
  'zh-TW': 'zh-TW',
  da: 'da-DK',
  nl: 'nl-NL',
  en: 'en-US',
  et: 'et-EE',
  fil: 'fil-PH',
  fi: 'fi',
  fr: 'fr-FR',
  de: 'de-DE',
  el: 'el-GR',
  he: 'he',
  hi: 'hi-IN',
  hu: 'hu',
  is: 'is',
  id: 'is',
  ga: 'ga-IE',
  it: 'it',
  ja: 'ja',
  ko: 'ko',
  lo: 'lo-LA',
  lv: 'lv',
  lt: 'lt',
  mg: 'mg',
  ms: 'ms-MY',
  mt: 'mt',
  mi: 'mi-NZ',
  mn: 'mn',
  ne: 'ne-NP',
  no: 'no-NO',
  ps: 'ps-AF',
  fa: 'fa-AF',
  pl: 'pl',
  pt: 'pt',
  ro: 'ro',
  ru: 'ru',
  sr: 'sr-SP',
  sk: 'sk',
  es: 'es-us',
  sw: 'sw-KE',
  sv: 'sv-SE',
  tl: 'tl-PH',
  tg: 'tg-TJ',
  ta: 'ta-LK',
  th: 'th',
  tr: 'tr',
  uk: 'uk-UA',
  ur: 'ur-PK',
  vi: 'vi-VN',
  cy: 'GB-WLS',
};
